image:
  - Visual Studio 2017

environment:
  global:
    CIBW_BEFORE_BUILD: python setup.py build_c_core
    CIBW_TEST_COMMAND: "cd {project} && python -m unittest"
    IGRAPH_EXTRA_CONFIGURE_ARGS: "--disable-graphml"
    PYTHON: "C:\\Python37"

  matrix:
    - CIBW_BUILD: "*-win32"
      # CPython 2.7 and 3.5 are skipped because they are not supported any
      # more. PyPy is skipped because we run into weird linking errors on
      # Windows and I have no idea how to get around it.
      CIBW_SKIP: "cp27-* cp35-* pp*"
      MSYSTEM: MINGW32
      PATH: C:\msys64\usr\bin;C:\msys64\mingw32\bin;C:\Windows\System32;C:\Windows;%PATH%
      TARGET_ARCH: "x86"

    - CIBW_BUILD: "*-win_amd64"
      # CPython 2.7 and 3.5 are skipped because they are not supported any
      # more. PyPy is skipped because we run into weird linking errors on
      # Windows and I have no idea how to get around it.
      CIBW_SKIP: "cp27-* cp35-* pp*"
      MSYSTEM: MINGW64
      PATH: C:\msys64\usr\bin;C:\msys64\mingw64\bin;C:\Windows\System32;C:\Windows;%PATH%
      TARGET_ARCH: "x64"

platform:
  - x64

install:
  # update msys2 keyring first
  - bash -lc "curl -O http://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz"
  - bash -lc "curl -O http://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig"
  - bash -lc "pacman --noconfirm -U msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz"

  # update msys2
  - bash -lc "pacman --needed --noconfirm -Sy pacman-mirrors"
  - bash -lc "pacman --noconfirm -Sy"
  - bash -lc "pacman --needed --noconfirm -S zstd"
  - bash -lc "pacman --needed --noconfirm -S autoconf automake bison flex libtool mingw-w64-x86_64-libtool mingw-w64-i686-libxml2 mingw-w64-x86_64-libxml2 zip"

  # prepare Python
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python --version"
  - "python -m pip install --upgrade pip"

  # install cibuildwheel
  - pip install cibuildwheel==1.6.1

before_build:
  - git submodule update --init --recursive

for:
  - matrix:
      only:
        - MSYSTEM: MINGW32
    build_script:
      - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
      - cibuildwheel --output-dir wheelhouse
  - matrix:
      only:
        - MSYSTEM: MINGW64
    build_script:
      - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
      - cibuildwheel --output-dir wheelhouse

artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels

